import type { Level } from "./types";

export const ASTRONOMY_LEVELS: Level[] = [
  // ── Solar System ──────────────────────────────────────────────────
  {
    id: "astro-ss-01",
    grade: 0,
    type: "solar-system",
    word: "Jupiter",
    prompt: "Which planet is the largest in our solar system?",
    choices: ["Saturn", "Jupiter", "Neptune", "Uranus"],
    answer: "Jupiter",
    definition: "The largest planet in our solar system, a giant made of gas.",
    contextSentence: "Jupiter is so large that all other planets could fit inside it.",
    hints: ["It is a gas giant and the fifth planet from the Sun.", "It has a giant storm called the Great Red Spot."],
    coach: "Jupiter is the biggest planet. It is a gas giant — so large that 1,300 Earths could fit inside it!"
  },
  {
    id: "astro-ss-02",
    grade: 0,
    type: "solar-system",
    word: "Mercury",
    prompt: "Which planet is closest to the Sun?",
    choices: ["Venus", "Earth", "Mercury", "Mars"],
    answer: "Mercury",
    definition: "The smallest planet and the one closest to the Sun.",
    contextSentence: "Mercury completes one orbit around the Sun in just 88 days.",
    hints: ["It is the smallest planet in our solar system.", "It has almost no atmosphere and is covered in craters."],
    coach: "Mercury is the closest planet to the Sun. Its year is only 88 Earth days long!"
  },
  {
    id: "astro-ss-03",
    grade: 0,
    type: "solar-system",
    word: "Saturn",
    prompt: "Which planet is famous for its spectacular ring system?",
    choices: ["Jupiter", "Uranus", "Neptune", "Saturn"],
    answer: "Saturn",
    definition: "The sixth planet from the Sun, known for its large, bright rings made of ice and rock.",
    contextSentence: "Saturn's rings are made of billions of chunks of ice and rock.",
    hints: ["It is the second largest planet.", "Its rings are visible through a small telescope."],
    coach: "Saturn is famous for its beautiful rings. The rings are made of ice and rock orbiting the planet."
  },
  {
    id: "astro-ss-04",
    grade: 0,
    type: "solar-system",
    word: "8",
    prompt: "How many planets are in our solar system?",
    choices: ["7", "8", "9", "10"],
    answer: "8",
    definition: "Our solar system has eight official planets: Mercury, Venus, Earth, Mars, Jupiter, Saturn, Uranus, and Neptune.",
    contextSentence: "In 2006, Pluto was reclassified as a dwarf planet, leaving 8 planets.",
    hints: ["Pluto was removed from the list in 2006.", "Count from Mercury to Neptune."],
    coach: "There are 8 planets: Mercury, Venus, Earth, Mars, Jupiter, Saturn, Uranus, Neptune. Pluto is now a dwarf planet."
  },
  {
    id: "astro-ss-05",
    grade: 0,
    type: "solar-system",
    word: "Venus",
    prompt: "Which is the hottest planet in our solar system?",
    choices: ["Mercury", "Venus", "Earth", "Mars"],
    answer: "Venus",
    definition: "The second planet from the Sun and the hottest planet, due to its thick greenhouse atmosphere.",
    contextSentence: "Venus is hotter than Mercury even though it is farther from the Sun.",
    hints: ["It is the second planet from the Sun.", "Its thick atmosphere traps heat like a greenhouse."],
    coach: "Venus is the hottest planet at around 465°C. Its thick atmosphere traps heat — even hotter than Mercury!"
  },
  {
    id: "astro-ss-06",
    grade: 0,
    type: "solar-system",
    word: "Asteroid Belt",
    prompt: "What lies between Mars and Jupiter?",
    choices: ["The Kuiper Belt", "The Asteroid Belt", "The Oort Cloud", "The Habitable Zone"],
    answer: "The Asteroid Belt",
    definition: "A region between Mars and Jupiter containing millions of rocky objects called asteroids.",
    contextSentence: "The Asteroid Belt is home to millions of space rocks of all sizes.",
    hints: ["It is a region full of rocky objects orbiting the Sun.", "Ceres, the largest dwarf planet, is found here."],
    coach: "The Asteroid Belt sits between Mars and Jupiter. It contains millions of rocky objects called asteroids."
  },
  {
    id: "astro-ss-07",
    grade: 0,
    type: "solar-system",
    word: "365.25 days",
    prompt: "How long does Earth take to complete one orbit around the Sun?",
    choices: ["24 hours", "30 days", "365.25 days", "100 days"],
    answer: "365.25 days",
    definition: "Earth takes about 365.25 days (one year) to travel all the way around the Sun.",
    contextSentence: "The extra 0.25 day is why we add a leap day every four years.",
    hints: ["It is the length of one year.", "The extra quarter day explains why we have leap years."],
    coach: "Earth takes 365.25 days to orbit the Sun. Every four years we add a leap day to catch up with that extra quarter day!"
  },
  {
    id: "astro-ss-08",
    grade: 0,
    type: "solar-system",
    word: "dwarf planet",
    prompt: "What is Pluto classified as?",
    choices: ["A planet", "A moon", "A dwarf planet", "An asteroid"],
    answer: "A dwarf planet",
    definition: "A dwarf planet orbits the Sun and has enough mass to be round, but has not cleared its orbit of other objects.",
    contextSentence: "Pluto was reclassified as a dwarf planet in 2006 by the International Astronomical Union.",
    hints: ["It is in the Kuiper Belt beyond Neptune.", "It was removed from the list of major planets in 2006."],
    coach: "Pluto is a dwarf planet. It orbits the Sun but shares its neighbourhood with many other icy objects in the Kuiper Belt."
  },
  {
    id: "astro-ss-09",
    grade: 0,
    type: "solar-system",
    word: "Uranus",
    prompt: "Which planet rotates on its side, with its axis tilted almost 98°?",
    choices: ["Saturn", "Neptune", "Uranus", "Jupiter"],
    answer: "Uranus",
    definition: "Uranus is unique because its axis is tilted so far that it essentially rolls around the Sun on its side.",
    contextSentence: "A season on Uranus can last over 20 years because of its extreme tilt.",
    hints: ["It is an ice giant, the seventh planet from the Sun.", "Its extreme tilt means each pole faces the Sun for decades."],
    coach: "Uranus is tilted nearly sideways at 98°, so it rolls around the Sun like a ball. Each pole has 42 years of sunlight followed by 42 years of darkness!"
  },
  {
    id: "astro-ss-10",
    grade: 0,
    type: "solar-system",
    word: "Moon",
    prompt: "What is the name of Earth's only natural satellite?",
    choices: ["Titan", "Europa", "Phobos", "Moon"],
    answer: "Moon",
    definition: "The Moon is a natural satellite that orbits Earth, about 384,400 km away.",
    contextSentence: "The Moon causes the ocean tides on Earth because of its gravity.",
    hints: ["It lights up the night sky and goes through phases.", "Humans first landed on it in 1969."],
    coach: "Earth has one natural satellite: the Moon. Its gravity pulls on Earth's oceans, creating tides."
  },

  // ── Stars ──────────────────────────────────────────────────────────
  {
    id: "astro-st-01",
    grade: 0,
    type: "stars",
    word: "yellow dwarf",
    prompt: "What type of star is our Sun?",
    choices: ["Red giant", "White dwarf", "Yellow dwarf", "Blue supergiant"],
    answer: "Yellow dwarf",
    definition: "A yellow dwarf (G-type star) is a medium-sized star with a surface temperature around 5,500°C.",
    contextSentence: "Our Sun is a yellow dwarf star in the middle of its life cycle.",
    hints: ["It is a medium-sized, middle-aged star.", "It is also called a G-type main-sequence star."],
    coach: "The Sun is a yellow dwarf star. It is about halfway through its 10-billion-year life. When it runs out of fuel, it will expand into a red giant."
  },
  {
    id: "astro-st-02",
    grade: 0,
    type: "stars",
    word: "Proxima Centauri",
    prompt: "What is the closest star to our solar system (other than the Sun)?",
    choices: ["Sirius", "Betelgeuse", "Proxima Centauri", "Vega"],
    answer: "Proxima Centauri",
    definition: "Proxima Centauri is a red dwarf star about 4.24 light-years from Earth, the nearest known star beyond our Sun.",
    contextSentence: "Even at the speed of light, it would take over 4 years to reach Proxima Centauri.",
    hints: ["It is part of the Alpha Centauri star system.", "It is a small red dwarf star."],
    coach: "Proxima Centauri is our nearest stellar neighbour at 4.24 light-years away. Despite being so close, it would take tens of thousands of years to travel there!"
  },
  {
    id: "astro-st-03",
    grade: 0,
    type: "stars",
    word: "supernova",
    prompt: "What happens when a very massive star runs out of fuel?",
    choices: ["It slowly fades out", "It explodes in a massive supernova", "It becomes a comet", "It splits into two stars"],
    answer: "It explodes in a massive supernova",
    definition: "A supernova is an enormous explosion that occurs when a massive star collapses at the end of its life.",
    contextSentence: "A supernova can briefly outshine an entire galaxy of billions of stars.",
    hints: ["It is one of the most powerful explosions in the universe.", "It can leave behind a neutron star or black hole."],
    coach: "When a massive star runs out of fuel, it collapses and explodes as a supernova — one of the brightest events in the universe!"
  },
  {
    id: "astro-st-04",
    grade: 0,
    type: "stars",
    word: "Sirius",
    prompt: "What is the brightest star visible in the night sky as seen from Earth?",
    choices: ["Polaris", "Betelgeuse", "Sirius", "Vega"],
    answer: "Sirius",
    definition: "Sirius, also called the Dog Star, is the brightest star in the night sky, about 8.6 light-years from Earth.",
    contextSentence: "Sirius is so bright that ancient Egyptians used it to predict the annual Nile flood.",
    hints: ["It is in the constellation Canis Major (the Big Dog).", "Ancient Egyptians considered it very important."],
    coach: "Sirius is the brightest star in the night sky. It is called the Dog Star because it is in the constellation Canis Major (the Big Dog)."
  },
  {
    id: "astro-st-05",
    grade: 0,
    type: "stars",
    word: "Milky Way",
    prompt: "What is the name of the galaxy that contains our solar system?",
    choices: ["Andromeda", "Triangulum", "Sombrero", "The Milky Way"],
    answer: "The Milky Way",
    definition: "The Milky Way is a spiral galaxy containing our solar system, home to over 200 billion stars.",
    contextSentence: "On a clear night, far from city lights, you can see the Milky Way as a glowing band across the sky.",
    hints: ["It looks like a glowing band of stars across the night sky.", "It is a spiral galaxy with a supermassive black hole at its centre."],
    coach: "We live in the Milky Way galaxy. It is a spiral galaxy with over 200 billion stars — and our Sun is just one of them!"
  },
  {
    id: "astro-st-06",
    grade: 0,
    type: "stars",
    word: "blue",
    prompt: "What colour are the hottest stars?",
    choices: ["Red", "Yellow", "Orange", "Blue"],
    answer: "Blue",
    definition: "Blue stars are the hottest stars, with surface temperatures above 25,000°C. Red stars are the coolest.",
    contextSentence: "A blue star is much hotter than our yellow Sun.",
    hints: ["Think of a flame: which part is hottest — the red part or the blue part?", "Cooler stars appear red or orange; hotter stars appear white or blue."],
    coach: "In stars, blue means hot and red means cool. Blue stars are the hottest, then white, then yellow, then orange, then red."
  },
  {
    id: "astro-st-07",
    grade: 0,
    type: "stars",
    word: "black hole",
    prompt: "What is a black hole?",
    choices: ["A star with no light", "A gap between galaxies", "A region where gravity is so strong that nothing, not even light, can escape", "A dark planet"],
    answer: "A region where gravity is so strong that nothing, not even light, can escape",
    definition: "A black hole is a region of space where gravity is so intense that nothing — not even light — can escape from it.",
    contextSentence: "Black holes often form when a massive star collapses at the end of its life.",
    hints: ["Even light cannot escape from it.", "They often form from the remains of massive stars."],
    coach: "A black hole is a place in space where gravity is so strong that not even light can escape. That's why it looks completely black!"
  },

  // ── Fun Facts ──────────────────────────────────────────────────────
  {
    id: "astro-ff-01",
    grade: 0,
    type: "fun-fact",
    word: "Venus",
    prompt: "On which planet is a single day longer than a full year?",
    choices: ["Mars", "Jupiter", "Venus", "Saturn"],
    answer: "Venus",
    definition: "Venus rotates so slowly that one day on Venus (243 Earth days) is longer than its year (225 Earth days).",
    contextSentence: "On Venus, the Sun rises in the west and sets in the east because it spins backwards.",
    hints: ["It is the second planet from the Sun.", "It also spins backwards compared to most planets."],
    coach: "Venus spins so slowly that one Venusian day is longer than its whole year. It also spins backwards, so the Sun rises in the west there!"
  },
  {
    id: "astro-ff-02",
    grade: 0,
    type: "fun-fact",
    word: "Great Red Spot",
    prompt: "The Great Red Spot on Jupiter is a storm that has been raging for more than how long?",
    choices: ["10 years", "100 years", "350+ years", "1,000 years"],
    answer: "350+ years",
    definition: "The Great Red Spot is a giant storm on Jupiter that has been observed for at least 350 years and is larger than Earth.",
    contextSentence: "The Great Red Spot is a storm so large that Earth could fit inside it.",
    hints: ["It was first observed in the 1600s.", "This storm is wider than planet Earth."],
    coach: "The Great Red Spot is a massive storm on Jupiter that is wider than Earth and has been spinning for over 350 years!"
  },
  {
    id: "astro-ff-03",
    grade: 0,
    type: "fun-fact",
    word: "8 minutes",
    prompt: "How long does light from the Sun take to reach Earth?",
    choices: ["8 seconds", "8 minutes", "8 hours", "8 days"],
    answer: "8 minutes",
    definition: "Light travels at about 300,000 km/s, and the Sun is about 150 million km away — so its light takes about 8 minutes to reach us.",
    contextSentence: "When you look at the Sun, you are seeing it as it was 8 minutes ago.",
    hints: ["Light travels at 300,000 km per second.", "The Sun is about 150 million km from Earth."],
    coach: "Light from the Sun takes about 8 minutes to reach Earth. So when you look at the Sun, you're seeing it as it was 8 minutes ago!"
  },
  {
    id: "astro-ff-04",
    grade: 0,
    type: "fun-fact",
    word: "no wind or water",
    prompt: "Why do footprints left on the Moon last for millions of years?",
    choices: ["The Moon is covered in ice", "There is no wind or water to erase them", "Moon rocks are very sticky", "The Moon spins very slowly"],
    answer: "There is no wind or water to erase them",
    definition: "The Moon has no atmosphere, so there is no wind or rain to wear away footprints or other marks on its surface.",
    contextSentence: "The footprints left by Apollo astronauts in 1969 are still there today.",
    hints: ["Think about what erodes footprints on Earth.", "The Moon has no atmosphere."],
    coach: "On Earth, wind and rain erase footprints quickly. The Moon has no atmosphere — no wind, no weather — so Apollo astronaut footprints will last for millions of years!"
  },
  {
    id: "astro-ff-05",
    grade: 0,
    type: "fun-fact",
    word: "silence",
    prompt: "Why is space completely silent?",
    choices: ["Space is too cold for sound", "Sound needs air to travel, and space is a vacuum", "Sounds travel too slowly in space", "Space absorbs all sound waves"],
    answer: "Sound needs air to travel, and space is a vacuum",
    definition: "Sound is a vibration that travels through matter (like air or water). Deep space is a vacuum with almost no matter, so sound cannot travel.",
    contextSentence: "In the film 'Alien', the tagline 'In space, no one can hear you scream' is scientifically correct.",
    hints: ["Sound is a wave that needs a medium to travel through.", "Space is almost completely empty — a vacuum."],
    coach: "Sound needs particles to travel through. Deep space is a vacuum — almost nothing there — so sound cannot travel. Space is completely silent!"
  },
  {
    id: "astro-ff-06",
    grade: 0,
    type: "fun-fact",
    word: "1,000,000",
    prompt: "Roughly how many Earths could fit inside the Sun?",
    choices: ["About 100", "About 1,000", "About 1,000,000", "About 1,000,000,000"],
    answer: "About 1,000,000",
    definition: "The Sun is so enormous that roughly one million Earths could fit inside it.",
    contextSentence: "The Sun contains about 99.8% of all the mass in our solar system.",
    hints: ["The Sun is by far the largest object in our solar system.", "The Sun contains 99.8% of the total mass of the solar system."],
    coach: "The Sun is huge — about 1.4 million km across. You could fit about one million Earths inside it. The Sun holds 99.8% of all the mass in our solar system!"
  },
  {
    id: "astro-ff-07",
    grade: 0,
    type: "fun-fact",
    word: "neutron star",
    prompt: "A teaspoon of material from a neutron star would weigh about how much on Earth?",
    choices: ["1 kilogram", "1 tonne", "1 billion tonnes", "1 gram"],
    answer: "1 billion tonnes",
    definition: "Neutron stars are incredibly dense. A teaspoon of neutron star material would weigh about a billion tonnes.",
    contextSentence: "Neutron stars are the collapsed cores of massive stars, packed with unimaginable density.",
    hints: ["Neutron stars are incredibly dense objects.", "They are the remnants of exploded massive stars."],
    coach: "Neutron stars are incredibly dense. A teaspoon of their material would weigh about 1 billion tonnes — as heavy as a mountain!"
  },

  // ── Astronomy Vocabulary ───────────────────────────────────────────
  {
    id: "astro-voc-01",
    grade: 0,
    type: "astronomy-vocab",
    word: "light-year",
    prompt: "What does the term 'light-year' measure?",
    choices: ["How long a year lasts in space", "The distance light travels in one year", "How bright a star is", "The speed of a planet"],
    answer: "The distance light travels in one year",
    definition: "A light-year is the distance that light travels in one year — about 9.46 trillion kilometres.",
    contextSentence: "The nearest star to our Sun is about 4.24 light-years away.",
    hints: ["It is a unit of distance, not time.", "Light travels at about 300,000 km per second."],
    coach: "A light-year measures distance, not time! It is the distance light travels in one year — about 9.46 trillion km. Scientists use it to measure distances between stars."
  },
  {
    id: "astro-voc-02",
    grade: 0,
    type: "astronomy-vocab",
    word: "orbit",
    prompt: "What does 'orbit' mean in astronomy?",
    choices: ["The centre of a planet", "The curved path one object takes around another due to gravity", "The explosion of a star", "The surface of the Moon"],
    answer: "The curved path one object takes around another due to gravity",
    definition: "An orbit is the curved path that a planet, moon, or satellite takes around a larger object due to gravity.",
    contextSentence: "Earth orbits the Sun once every 365.25 days.",
    hints: ["It involves one object moving around another.", "Gravity keeps the object on this path."],
    coach: "An orbit is the path one object takes around another because of gravity. Earth orbits the Sun, and the Moon orbits Earth."
  },
  {
    id: "astro-voc-03",
    grade: 0,
    type: "astronomy-vocab",
    word: "nebula",
    prompt: "What is a nebula?",
    choices: ["A type of comet", "A small moon", "A cloud of gas and dust in space where stars can form", "A dwarf planet"],
    answer: "A cloud of gas and dust in space where stars can form",
    definition: "A nebula is a giant cloud of gas and dust in space. New stars are often born inside nebulae.",
    contextSentence: "The famous Orion Nebula is a stellar nursery where new stars are being born.",
    hints: ["It is often called a 'stellar nursery'.", "It is made of gas and dust floating in space."],
    coach: "A nebula is a cloud of gas and dust in space. New stars form inside nebulae — that's why they're called stellar nurseries!"
  },
  {
    id: "astro-voc-04",
    grade: 0,
    type: "astronomy-vocab",
    word: "eclipse",
    prompt: "What is a solar eclipse?",
    choices: ["When a comet passes by Earth", "When the Moon blocks the Sun's light from reaching Earth", "When a star explodes", "When Earth passes through asteroid belt"],
    answer: "When the Moon blocks the Sun's light from reaching Earth",
    definition: "A solar eclipse occurs when the Moon passes between the Sun and Earth, blocking some or all of the Sun's light.",
    contextSentence: "During a total solar eclipse, the sky goes dark in the middle of the day.",
    hints: ["It involves the Moon, Sun, and Earth lining up.", "During a total one, the sky goes dark in the daytime."],
    coach: "A solar eclipse happens when the Moon passes between the Sun and Earth, blocking the Sun's light. During a total solar eclipse, the sky goes dark in the middle of the day!"
  },
  {
    id: "astro-voc-05",
    grade: 0,
    type: "astronomy-vocab",
    word: "gravity",
    prompt: "What is gravity?",
    choices: ["The glow of a star", "A force that attracts objects with mass toward each other", "The path of a planet around the Sun", "The tail of a comet"],
    answer: "A force that attracts objects with mass toward each other",
    definition: "Gravity is a natural force of attraction between any two objects that have mass. The more mass, the stronger the pull.",
    contextSentence: "Gravity keeps Earth in orbit around the Sun and the Moon in orbit around Earth.",
    hints: ["It is the force that keeps your feet on the ground.", "Isaac Newton described it when an apple fell from a tree."],
    coach: "Gravity is the force that pulls objects with mass toward each other. It keeps planets orbiting the Sun, moons orbiting planets, and you firmly on the ground!"
  },
  {
    id: "astro-voc-06",
    grade: 0,
    type: "astronomy-vocab",
    word: "comet",
    prompt: "What is a comet?",
    choices: ["A rocky planet", "A ball of ice, dust, and rock that orbits the Sun and forms a tail when near the Sun", "A type of black hole", "A satellite orbiting Earth"],
    answer: "A ball of ice, dust, and rock that orbits the Sun and forms a tail when near the Sun",
    definition: "A comet is a small icy body that orbits the Sun. When it gets close to the Sun, some of it vaporises, forming a bright tail.",
    contextSentence: "Halley's Comet passes close to Earth about every 75–76 years.",
    hints: ["It forms a bright glowing tail when it gets close to the Sun.", "Halley's is the most famous one."],
    coach: "Comets are balls of ice and rock. When they get close to the Sun, the ice turns to gas and forms a long glowing tail that can stretch millions of kilometres!"
  },
  {
    id: "astro-voc-07",
    grade: 0,
    type: "astronomy-vocab",
    word: "meteor",
    prompt: "What is a meteor?",
    choices: ["A planet without moons", "A type of galaxy", "A space rock that burns up and glows as it enters Earth's atmosphere", "A cloud of gas in space"],
    answer: "A space rock that burns up and glows as it enters Earth's atmosphere",
    definition: "A meteor (shooting star) is a piece of space debris that burns up when it enters Earth's atmosphere, creating a bright streak of light.",
    contextSentence: "You can often see meteors during a meteor shower, when Earth passes through a trail of debris.",
    hints: ["People often call it a 'shooting star'.", "It glows because of friction with Earth's atmosphere."],
    coach: "A meteor is a piece of space rock that burns up in Earth's atmosphere, making a bright streak called a 'shooting star'. If it lands on Earth, it is called a meteorite."
  },
  {
    id: "astro-voc-08",
    grade: 0,
    type: "astronomy-vocab",
    word: "astronomer",
    prompt: "What is an astronomer?",
    choices: ["A person who travels to space", "A scientist who studies stars, planets, and other objects in the universe", "A person who builds rockets", "A person who studies weather"],
    answer: "A scientist who studies stars, planets, and other objects in the universe",
    definition: "An astronomer is a scientist who observes and studies celestial objects such as stars, planets, galaxies, and other phenomena in the universe.",
    contextSentence: "The astronomer used a telescope to study a distant galaxy.",
    hints: ["The prefix 'astro-' means star or space.", "They use telescopes to do their work."],
    coach: "An astronomer is a scientist who studies the universe — stars, planets, galaxies, and everything else in space. Astronomy is one of the oldest sciences!"
  },
  {
    id: "astro-voc-09",
    grade: 0,
    type: "astronomy-vocab",
    word: "galaxy",
    prompt: "What is a galaxy?",
    choices: ["A single large star", "A massive system of stars, gas, dust, and dark matter bound together by gravity", "A large comet", "A ring of asteroids"],
    answer: "A massive system of stars, gas, dust, and dark matter bound together by gravity",
    definition: "A galaxy is a huge collection of stars, gas, dust, and dark matter held together by gravity. There are billions of galaxies in the observable universe.",
    contextSentence: "Our Milky Way galaxy contains over 200 billion stars.",
    hints: ["It contains billions of stars.", "Our solar system lives inside one called the Milky Way."],
    coach: "A galaxy is a giant collection of billions of stars, gas, and dust held together by gravity. Our galaxy, the Milky Way, contains over 200 billion stars — and there are billions of other galaxies in the universe!"
  }
];
