import type { Level } from "./types";

export const MATH_KANGAROO_CATEGORY_LABELS: Record<string, string> = {
  all: "All Grades",
  "kangaroo-g5": "Grade 5",
  "kangaroo-g6": "Grade 6",
  "kangaroo-g7": "Grade 7",
  "kangaroo-g8": "Grade 8"
};

export const MATH_KANGAROO_LEVELS: Level[] = [
  // Grade 5
  {
    id: "mk-g5-01",
    grade: 5,
    type: "kangaroo-g5",
    word: "36",
    prompt: "A rectangle has side lengths 4 cm and 9 cm. What is its area?",
    choices: ["13", "26", "36", "72"],
    answer: "36",
    definition: "Area of a rectangle is length multiplied by width.",
    contextSentence: "4 × 9 gives the number of square units inside the rectangle.",
    hints: ["Use area = length × width.", "4 × 9 = ?"],
    coach: "Correct. 4 × 9 = 36 square centimeters."
  },
  {
    id: "mk-g5-02",
    grade: 5,
    type: "kangaroo-g5",
    word: "7",
    prompt: "What is the remainder when 73 is divided by 11?",
    choices: ["5", "6", "7", "8"],
    answer: "7",
    definition: "Remainder is what is left after equal division.",
    contextSentence: "73 = 11 × 6 + 7.",
    hints: ["Find the biggest multiple of 11 below 73.", "11 × 6 = 66."],
    coach: "Right. 73 − 66 = 7, so the remainder is 7."
  },
  {
    id: "mk-g5-03",
    grade: 5,
    type: "kangaroo-g5",
    word: "24",
    prompt: "How many edges does a cube have?",
    choices: ["8", "12", "18", "24"],
    answer: "12",
    definition: "A cube has 6 faces, 8 vertices, and 12 edges.",
    contextSentence: "Each face is a square, and edges are shared by two faces.",
    hints: ["Recall cube properties.", "Do not confuse edges with vertices."],
    coach: "A cube has 12 edges."
  },
  {
    id: "mk-g5-04",
    grade: 5,
    type: "kangaroo-g5",
    word: "3/4",
    prompt: "Which fraction is equivalent to 0.75?",
    choices: ["1/4", "2/3", "3/4", "4/5"],
    answer: "3/4",
    definition: "0.75 means seventy-five hundredths.",
    contextSentence: "75/100 simplifies to 3/4.",
    hints: ["Write 0.75 as 75/100.", "Simplify by dividing by 25."],
    coach: "Correct. 0.75 = 75/100 = 3/4."
  },
  {
    id: "mk-g5-05",
    grade: 5,
    type: "kangaroo-g5",
    word: "42",
    prompt: "If 6 pens cost 30 dollars, how much do 8 pens cost at the same rate?",
    choices: ["36", "40", "42", "48"],
    answer: "40",
    definition: "Use unit rate then scale.",
    contextSentence: "Each pen costs 5 dollars.",
    hints: ["First find cost of 1 pen.", "Then multiply by 8."],
    coach: "One pen costs 30 ÷ 6 = 5, so 8 pens cost 40."
  },
  {
    id: "mk-g5-06",
    grade: 5,
    type: "kangaroo-g5",
    word: "14",
    prompt: "What is the sum of the first five even positive numbers?",
    choices: ["20", "24", "30", "40"],
    answer: "30",
    definition: "First five even positive numbers are 2, 4, 6, 8, 10.",
    contextSentence: "2 + 4 + 6 + 8 + 10 = 30.",
    hints: ["List them in order.", "Add carefully."],
    coach: "Correct. The sum is 30."
  },
  {
    id: "mk-g5-07",
    grade: 5,
    type: "kangaroo-g5",
    word: "90",
    prompt: "A clock shows 3:00. What is the smaller angle between the hands?",
    choices: ["60°", "75°", "90°", "120°"],
    answer: "90°",
    definition: "At 3:00, minute hand is at 12 and hour hand at 3.",
    contextSentence: "That makes a right angle.",
    hints: ["Each hour mark is 30°.", "From 12 to 3 is 3 marks."],
    coach: "3 × 30° = 90°."
  },
  {
    id: "mk-g5-08",
    grade: 5,
    type: "kangaroo-g5",
    word: "15",
    prompt: "How many two-digit numbers can be formed using digits 1, 3, and 5 without repetition?",
    choices: ["3", "6", "9", "15"],
    answer: "6",
    definition: "Count permutations of 3 digits taken 2 at a time.",
    contextSentence: "Choices: 13, 15, 31, 35, 51, 53.",
    hints: ["Choose tens digit then ones digit.", "3 choices then 2 choices."],
    coach: "3 × 2 = 6 numbers."
  },
  {
    id: "mk-g5-09",
    grade: 5,
    type: "kangaroo-g5",
    word: "48",
    prompt: "A number is doubled and then 6 is added to get 30. What is the number?",
    choices: ["9", "10", "11", "12"],
    answer: "12",
    definition: "Let x be the number: 2x + 6 = 30.",
    contextSentence: "Then 2x = 24 and x = 12.",
    hints: ["Undo +6 first.", "Then divide by 2."],
    coach: "(30 − 6) ÷ 2 = 12."
  },
  {
    id: "mk-g5-10",
    grade: 5,
    type: "kangaroo-g5",
    word: "16",
    prompt: "How many small 1×1 squares are in a 4×4 grid?",
    choices: ["8", "12", "16", "20"],
    answer: "16",
    definition: "A 4 by 4 grid has 4 rows and 4 columns of unit squares.",
    contextSentence: "Total small squares = 4 × 4.",
    hints: ["Count rows and columns.", "Multiply 4 by 4."],
    coach: "Correct. There are 16 unit squares."
  },

  // Grade 6
  {
    id: "mk-g6-01",
    grade: 6,
    type: "kangaroo-g6",
    word: "24",
    prompt: "If 40% of a number is 24, what is the number?",
    choices: ["48", "56", "60", "72"],
    answer: "60",
    definition: "40% means 0.4.",
    contextSentence: "0.4 × N = 24, so N = 24 ÷ 0.4 = 60.",
    hints: ["Convert percent to decimal.", "Divide by 0.4."],
    coach: "Correct. The original number is 60."
  },
  {
    id: "mk-g6-02",
    grade: 6,
    type: "kangaroo-g6",
    word: "18",
    prompt: "What is the least common multiple of 6 and 9?",
    choices: ["12", "18", "27", "36"],
    answer: "18",
    definition: "LCM is the smallest positive number divisible by both numbers.",
    contextSentence: "18 is divisible by 6 and by 9.",
    hints: ["List multiples of 6 and 9.", "Pick the first common one."],
    coach: "The least common multiple is 18."
  },
  {
    id: "mk-g6-03",
    grade: 6,
    type: "kangaroo-g6",
    word: "5/6",
    prompt: "Which is greater: 4/5 or 5/6?",
    choices: ["4/5", "5/6", "They are equal", "Cannot compare"],
    answer: "5/6",
    definition: "Compare by common denominator or decimals.",
    contextSentence: "4/5 = 0.8 and 5/6 ≈ 0.833.",
    hints: ["Convert to decimals.", "0.833 is bigger than 0.8."],
    coach: "5/6 is greater."
  },
  {
    id: "mk-g6-04",
    grade: 6,
    type: "kangaroo-g6",
    word: "72",
    prompt: "A triangle has angles 35° and 73°. What is the third angle?",
    choices: ["62°", "68°", "72°", "82°"],
    answer: "72°",
    definition: "Sum of angles in a triangle is 180°.",
    contextSentence: "180 − 35 − 73 = 72.",
    hints: ["Use 180° total.", "Subtract the two known angles."],
    coach: "The third angle is 72°."
  },
  {
    id: "mk-g6-05",
    grade: 6,
    type: "kangaroo-g6",
    word: "7",
    prompt: "The ratio of boys to girls is 3:4. If there are 12 boys, how many girls are there?",
    choices: ["12", "14", "16", "18"],
    answer: "16",
    definition: "Scale ratios by the same factor.",
    contextSentence: "3 parts become 12, so multiply by 4; girls = 4 × 4 = 16.",
    hints: ["3 -> 12 means factor 4.", "Apply same factor to 4."],
    coach: "Correct. Girls = 16."
  },
  {
    id: "mk-g6-06",
    grade: 6,
    type: "kangaroo-g6",
    word: "5",
    prompt: "How many diagonals does a pentagon have?",
    choices: ["3", "4", "5", "6"],
    answer: "5",
    definition: "Number of diagonals in n-gon is n(n−3)/2.",
    contextSentence: "For n=5: 5×2/2 = 5.",
    hints: ["Use n(n−3)/2.", "Plug n = 5."],
    coach: "A pentagon has 5 diagonals."
  },
  {
    id: "mk-g6-07",
    grade: 6,
    type: "kangaroo-g6",
    word: "49",
    prompt: "What is 25% of 196?",
    choices: ["39", "49", "59", "69"],
    answer: "49",
    definition: "25% is one quarter.",
    contextSentence: "196 ÷ 4 = 49.",
    hints: ["Think of quarter.", "Divide by 4."],
    coach: "Correct. 25% of 196 is 49."
  },
  {
    id: "mk-g6-08",
    grade: 6,
    type: "kangaroo-g6",
    word: "14",
    prompt: "A sequence starts 2, 5, 8, 11, ... What is the 5th term?",
    choices: ["13", "14", "15", "16"],
    answer: "14",
    definition: "This arithmetic sequence increases by 3 each time.",
    contextSentence: "Terms: 2, 5, 8, 11, 14.",
    hints: ["Add 3 repeatedly.", "Find 5th value."],
    coach: "The 5th term is 14."
  },
  {
    id: "mk-g6-09",
    grade: 6,
    type: "kangaroo-g6",
    word: "3",
    prompt: "How many integers are strictly between -2 and 2?",
    choices: ["2", "3", "4", "5"],
    answer: "3",
    definition: "Strictly between excludes endpoints.",
    contextSentence: "The integers are -1, 0, 1.",
    hints: ["Do not include -2 or 2.", "List the integers."],
    coach: "There are 3 integers: -1, 0, 1."
  },
  {
    id: "mk-g6-10",
    grade: 6,
    type: "kangaroo-g6",
    word: "6",
    prompt: "A fair die is rolled once. What is the probability of getting an even number?",
    choices: ["1/6", "1/3", "1/2", "2/3"],
    answer: "1/2",
    definition: "Even outcomes on a die are 2, 4, 6.",
    contextSentence: "3 favorable outcomes out of 6 total gives 3/6 = 1/2.",
    hints: ["Count even faces.", "Simplify the fraction."],
    coach: "Probability is 1/2."
  },

  // Grade 7
  {
    id: "mk-g7-01",
    grade: 7,
    type: "kangaroo-g7",
    word: "-7",
    prompt: "Evaluate: -3 + 5 - 9.",
    choices: ["-11", "-9", "-7", "7"],
    answer: "-7",
    definition: "Add integers carefully with signs.",
    contextSentence: "-3 + 5 = 2, and 2 - 9 = -7.",
    hints: ["Compute left to right.", "Watch signs."],
    coach: "Correct. The value is -7."
  },
  {
    id: "mk-g7-02",
    grade: 7,
    type: "kangaroo-g7",
    word: "13",
    prompt: "If 3x + 4 = 43, what is x?",
    choices: ["11", "12", "13", "14"],
    answer: "13",
    definition: "Solve linear equation by inverse operations.",
    contextSentence: "3x = 39 so x = 13.",
    hints: ["Subtract 4 first.", "Then divide by 3."],
    coach: "x = 13."
  },
  {
    id: "mk-g7-03",
    grade: 7,
    type: "kangaroo-g7",
    word: "81",
    prompt: "What is 3^4?",
    choices: ["27", "54", "64", "81"],
    answer: "81",
    definition: "3^4 means 3 multiplied by itself 4 times.",
    contextSentence: "3 × 3 × 3 × 3 = 81.",
    hints: ["3^2 = 9.", "Then multiply by 9 again."],
    coach: "Correct. 3^4 = 81."
  },
  {
    id: "mk-g7-04",
    grade: 7,
    type: "kangaroo-g7",
    word: "84",
    prompt: "The sum of two numbers is 30 and their difference is 6. What is the larger number?",
    choices: ["12", "15", "18", "24"],
    answer: "18",
    definition: "Use system with sum and difference.",
    contextSentence: "(30 + 6)/2 = 18 for the larger number.",
    hints: ["Add sum and difference.", "Then divide by 2."],
    coach: "Larger number is 18."
  },
  {
    id: "mk-g7-05",
    grade: 7,
    type: "kangaroo-g7",
    word: "28",
    prompt: "A circle has radius 7. Using π = 22/7, what is its circumference?",
    choices: ["14", "22", "28", "44"],
    answer: "44",
    definition: "Circumference is 2πr.",
    contextSentence: "2 × (22/7) × 7 = 44.",
    hints: ["Use 2πr.", "Cancel 7 in (22/7) × 7."],
    coach: "The circumference is 44."
  },
  {
    id: "mk-g7-06",
    grade: 7,
    type: "kangaroo-g7",
    word: "15",
    prompt: "How many prime numbers are there between 10 and 30?",
    choices: ["5", "6", "7", "8"],
    answer: "6",
    definition: "Prime numbers have exactly two positive divisors.",
    contextSentence: "Primes are 11, 13, 17, 19, 23, 29.",
    hints: ["List odd numbers and test divisibility.", "Remember 2 is not in range."],
    coach: "There are 6 such prime numbers."
  },
  {
    id: "mk-g7-07",
    grade: 7,
    type: "kangaroo-g7",
    word: "12",
    prompt: "A bag has 3 red, 2 blue, and 5 green balls. What is the probability of drawing a blue ball?",
    choices: ["1/10", "1/5", "2/5", "1/2"],
    answer: "1/5",
    definition: "Probability = favorable outcomes / total outcomes.",
    contextSentence: "2 blue out of 10 total gives 2/10 = 1/5.",
    hints: ["Find total balls first.", "Simplify fraction."],
    coach: "Probability is 1/5."
  },
  {
    id: "mk-g7-08",
    grade: 7,
    type: "kangaroo-g7",
    word: "24",
    prompt: "What is the value of |−18 + 6|?",
    choices: ["−12", "12", "18", "24"],
    answer: "12",
    definition: "Absolute value is distance from 0.",
    contextSentence: "−18 + 6 = −12, and |−12| = 12.",
    hints: ["Compute inside first.", "Then apply absolute value."],
    coach: "Correct. The value is 12."
  },
  {
    id: "mk-g7-09",
    grade: 7,
    type: "kangaroo-g7",
    word: "2",
    prompt: "If a:b = 4:7 and b = 21, what is a?",
    choices: ["8", "10", "12", "14"],
    answer: "12",
    definition: "Scale ratio parts to actual values.",
    contextSentence: "7 parts = 21 so 1 part = 3, then 4 parts = 12.",
    hints: ["Find one ratio part.", "Multiply by 4."],
    coach: "a = 12."
  },
  {
    id: "mk-g7-10",
    grade: 7,
    type: "kangaroo-g7",
    word: "5",
    prompt: "What is the sum of interior angles of a pentagon?",
    choices: ["360°", "450°", "540°", "720°"],
    answer: "540°",
    definition: "Sum of interior angles is (n−2)×180°.",
    contextSentence: "For n=5: (5−2)×180 = 540°.",
    hints: ["Use (n−2)×180.", "Set n = 5."],
    coach: "Pentagon interior-angle sum is 540°."
  },

  // Grade 8
  {
    id: "mk-g8-01",
    grade: 8,
    type: "kangaroo-g8",
    word: "4",
    prompt: "Solve for x: 2(x − 3) = 3x − 7.",
    choices: ["1", "2", "3", "4"],
    answer: "1",
    definition: "Expand and isolate x.",
    contextSentence: "2x−6 = 3x−7 gives x = 1.",
    hints: ["Move x terms to one side.", "Move constants to the other."],
    coach: "Correct. x = 1."
  },
  {
    id: "mk-g8-02",
    grade: 8,
    type: "kangaroo-g8",
    word: "25",
    prompt: "What is the value of (a + b)^2 when a = 3 and b = 2?",
    choices: ["13", "20", "25", "36"],
    answer: "25",
    definition: "Substitute values directly.",
    contextSentence: "(3 + 2)^2 = 5^2 = 25.",
    hints: ["Add first.", "Then square."],
    coach: "The value is 25."
  },
  {
    id: "mk-g8-03",
    grade: 8,
    type: "kangaroo-g8",
    word: "3",
    prompt: "A right triangle has legs 6 and 8. What is the hypotenuse?",
    choices: ["9", "10", "11", "12"],
    answer: "10",
    definition: "Use Pythagorean theorem.",
    contextSentence: "6^2 + 8^2 = 36 + 64 = 100, so hypotenuse = 10.",
    hints: ["Compute squares.", "Take square root at the end."],
    coach: "Hypotenuse is 10."
  },
  {
    id: "mk-g8-04",
    grade: 8,
    type: "kangaroo-g8",
    word: "2/3",
    prompt: "A number increases from 45 to 60. What is the percentage increase?",
    choices: ["25%", "30%", "33 1/3%", "40%"],
    answer: "33 1/3%",
    definition: "Percent increase = change/original × 100%.",
    contextSentence: "Change is 15, and 15/45 = 1/3 = 33 1/3%.",
    hints: ["Find increase first.", "Divide by original 45."],
    coach: "Correct. Increase is 33 1/3%."
  },
  {
    id: "mk-g8-05",
    grade: 8,
    type: "kangaroo-g8",
    word: "120",
    prompt: "How many different 3-letter arrangements can be made from A, B, C, D without repetition?",
    choices: ["12", "18", "24", "36"],
    answer: "24",
    definition: "Permutations of 4 items taken 3 at a time.",
    contextSentence: "4 × 3 × 2 = 24.",
    hints: ["Choose first, second, third positions.", "No repetition allowed."],
    coach: "There are 24 arrangements."
  },
  {
    id: "mk-g8-06",
    grade: 8,
    type: "kangaroo-g8",
    word: "7",
    prompt: "If f(x) = 2x + 1, what is f(5) − f(2)?",
    choices: ["4", "5", "6", "7"],
    answer: "6",
    definition: "Evaluate function at two inputs and subtract.",
    contextSentence: "f(5)=11 and f(2)=5, difference is 6.",
    hints: ["Compute each function value.", "Then subtract."],
    coach: "Correct. f(5) − f(2) = 6."
  },
  {
    id: "mk-g8-07",
    grade: 8,
    type: "kangaroo-g8",
    word: "64",
    prompt: "What is 2^6 × 2^3?",
    choices: ["2^9", "2^18", "64", "512"],
    answer: "2^9",
    definition: "When multiplying same base, add exponents.",
    contextSentence: "2^6 × 2^3 = 2^(6+3) = 2^9.",
    hints: ["Use exponent rule.", "You can also evaluate numerically."],
    coach: "Correct form is 2^9 (which equals 512)."
  },
  {
    id: "mk-g8-08",
    grade: 8,
    type: "kangaroo-g8",
    word: "9",
    prompt: "The mean of five numbers is 18. If four numbers are 12, 16, 20, 22, what is the fifth number?",
    choices: ["18", "20", "22", "24"],
    answer: "20",
    definition: "Mean = total / count.",
    contextSentence: "Total needed is 5×18=90; known sum is 70, so fifth is 20.",
    hints: ["Find required total first.", "Subtract known sum."],
    coach: "The fifth number is 20."
  },
  {
    id: "mk-g8-09",
    grade: 8,
    type: "kangaroo-g8",
    word: "45",
    prompt: "In a sequence 3, 6, 12, 24, ... what is the 6th term?",
    choices: ["48", "72", "96", "192"],
    answer: "96",
    definition: "Each term doubles.",
    contextSentence: "Terms are 3,6,12,24,48,96.",
    hints: ["Multiply by 2 each step.", "Count to the 6th term."],
    coach: "The 6th term is 96."
  },
  {
    id: "mk-g8-10",
    grade: 8,
    type: "kangaroo-g8",
    word: "11",
    prompt: "A box has 4 red and 6 white balls. Two balls are drawn without replacement. What is the probability both are red?",
    choices: ["1/5", "2/15", "1/3", "3/10"],
    answer: "2/15",
    definition: "Without replacement multiply dependent probabilities.",
    contextSentence: "(4/10)×(3/9)=12/90=2/15.",
    hints: ["First red then second red.", "Simplify final fraction."],
    coach: "Probability is 2/15."
  },

  // Extra Practice Expansion (Grades 5-8)
  {
    id: "mk-g5-11",
    grade: 5,
    type: "kangaroo-g5",
    word: "38",
    prompt: "What is 18 + 20?",
    choices: ["38", "36", "41", "44"],
    answer: "38",
    definition: "Solve using grade-level arithmetic and reasoning.",
    contextSentence: "This is a Math Kangaroo style practice question for Grade 5.",
    hints: ["Identify the operation first.", "Check units and compute carefully."],
    coach: "Correct. The answer is 38."
  },
  {
    id: "mk-g5-12",
    grade: 5,
    type: "kangaroo-g5",
    word: "32",
    prompt: "What is 8 × 4?",
    choices: ["32", "29", "36", "40"],
    answer: "32",
    definition: "Solve using grade-level arithmetic and reasoning.",
    contextSentence: "This is a Math Kangaroo style practice question for Grade 5.",
    hints: ["Identify the operation first.", "Check units and compute carefully."],
    coach: "Correct. The answer is 32."
  },
  {
    id: "mk-g5-13",
    grade: 5,
    type: "kangaroo-g5",
    word: "30",
    prompt: "A rectangle is 10 cm by 5 cm. What is its perimeter?",
    choices: ["30", "15", "50", "25"],
    answer: "30",
    definition: "Solve using grade-level arithmetic and reasoning.",
    contextSentence: "This is a Math Kangaroo style practice question for Grade 5.",
    hints: ["Identify the operation first.", "Check units and compute carefully."],
    coach: "Correct. The answer is 30."
  },
  {
    id: "mk-g5-14",
    grade: 5,
    type: "kangaroo-g5",
    word: "24",
    prompt: "A rectangle is 8 cm by 3 cm. What is its area?",
    choices: ["24", "11", "22", "34"],
    answer: "24",
    definition: "Solve using grade-level arithmetic and reasoning.",
    contextSentence: "This is a Math Kangaroo style practice question for Grade 5.",
    hints: ["Identify the operation first.", "Check units and compute carefully."],
    coach: "Correct. The answer is 24."
  },
  {
    id: "mk-g5-15",
    grade: 5,
    type: "kangaroo-g5",
    word: "9",
    prompt: "What is 1/2 of 18?",
    choices: ["11", "8", "9", "13"],
    answer: "9",
    definition: "Solve using grade-level arithmetic and reasoning.",
    contextSentence: "This is a Math Kangaroo style practice question for Grade 5.",
    hints: ["Identify the operation first.", "Check units and compute carefully."],
    coach: "Correct. The answer is 9."
  },
  {
    id: "mk-g5-16",
    grade: 5,
    type: "kangaroo-g5",
    word: "48",
    prompt: "What is 23 + 25?",
    choices: ["48", "46", "51", "54"],
    answer: "48",
    definition: "Solve using grade-level arithmetic and reasoning.",
    contextSentence: "This is a Math Kangaroo style practice question for Grade 5.",
    hints: ["Identify the operation first.", "Check units and compute carefully."],
    coach: "Correct. The answer is 48."
  },
  {
    id: "mk-g5-17",
    grade: 5,
    type: "kangaroo-g5",
    word: "54",
    prompt: "What is 6 × 9?",
    choices: ["54", "51", "58", "62"],
    answer: "54",
    definition: "Solve using grade-level arithmetic and reasoning.",
    contextSentence: "This is a Math Kangaroo style practice question for Grade 5.",
    hints: ["Identify the operation first.", "Check units and compute carefully."],
    coach: "Correct. The answer is 54."
  },
  {
    id: "mk-g5-18",
    grade: 5,
    type: "kangaroo-g5",
    word: "24",
    prompt: "A rectangle is 7 cm by 5 cm. What is its perimeter?",
    choices: ["24", "12", "35", "19"],
    answer: "24",
    definition: "Solve using grade-level arithmetic and reasoning.",
    contextSentence: "This is a Math Kangaroo style practice question for Grade 5.",
    hints: ["Identify the operation first.", "Check units and compute carefully."],
    coach: "Correct. The answer is 24."
  },
  {
    id: "mk-g5-19",
    grade: 5,
    type: "kangaroo-g5",
    word: "32",
    prompt: "A rectangle is 4 cm by 8 cm. What is its area?",
    choices: ["32", "12", "24", "42"],
    answer: "32",
    definition: "Solve using grade-level arithmetic and reasoning.",
    contextSentence: "This is a Math Kangaroo style practice question for Grade 5.",
    hints: ["Identify the operation first.", "Check units and compute carefully."],
    coach: "Correct. The answer is 32."
  },
  {
    id: "mk-g5-20",
    grade: 5,
    type: "kangaroo-g5",
    word: "7",
    prompt: "What is 1/2 of 14?",
    choices: ["9", "6", "7", "11"],
    answer: "7",
    definition: "Solve using grade-level arithmetic and reasoning.",
    contextSentence: "This is a Math Kangaroo style practice question for Grade 5.",
    hints: ["Identify the operation first.", "Check units and compute carefully."],
    coach: "Correct. The answer is 7."
  },
  {
    id: "mk-g5-21",
    grade: 5,
    type: "kangaroo-g5",
    word: "58",
    prompt: "What is 28 + 30?",
    choices: ["58", "56", "61", "64"],
    answer: "58",
    definition: "Solve using grade-level arithmetic and reasoning.",
    contextSentence: "This is a Math Kangaroo style practice question for Grade 5.",
    hints: ["Identify the operation first.", "Check units and compute carefully."],
    coach: "Correct. The answer is 58."
  },
  {
    id: "mk-g5-22",
    grade: 5,
    type: "kangaroo-g5",
    word: "32",
    prompt: "What is 4 × 8?",
    choices: ["32", "29", "36", "40"],
    answer: "32",
    definition: "Solve using grade-level arithmetic and reasoning.",
    contextSentence: "This is a Math Kangaroo style practice question for Grade 5.",
    hints: ["Identify the operation first.", "Check units and compute carefully."],
    coach: "Correct. The answer is 32."
  },
  {
    id: "mk-g5-23",
    grade: 5,
    type: "kangaroo-g5",
    word: "34",
    prompt: "A rectangle is 12 cm by 5 cm. What is its perimeter?",
    choices: ["34", "17", "60", "29"],
    answer: "34",
    definition: "Solve using grade-level arithmetic and reasoning.",
    contextSentence: "This is a Math Kangaroo style practice question for Grade 5.",
    hints: ["Identify the operation first.", "Check units and compute carefully."],
    coach: "Correct. The answer is 34."
  },
  {
    id: "mk-g5-24",
    grade: 5,
    type: "kangaroo-g5",
    word: "54",
    prompt: "A rectangle is 9 cm by 6 cm. What is its area?",
    choices: ["54", "15", "30", "64"],
    answer: "54",
    definition: "Solve using grade-level arithmetic and reasoning.",
    contextSentence: "This is a Math Kangaroo style practice question for Grade 5.",
    hints: ["Identify the operation first.", "Check units and compute carefully."],
    coach: "Correct. The answer is 54."
  },
  {
    id: "mk-g5-25",
    grade: 5,
    type: "kangaroo-g5",
    word: "9.5",
    prompt: "What is 1/2 of 19?",
    choices: ["11.5", "8.5", "9.5", "13.5"],
    answer: "9.5",
    definition: "Solve using grade-level arithmetic and reasoning.",
    contextSentence: "This is a Math Kangaroo style practice question for Grade 5.",
    hints: ["Identify the operation first.", "Check units and compute carefully."],
    coach: "Correct. The answer is 9.5."
  },
  {
    id: "mk-g5-26",
    grade: 5,
    type: "kangaroo-g5",
    word: "68",
    prompt: "What is 33 + 35?",
    choices: ["68", "66", "71", "74"],
    answer: "68",
    definition: "Solve using grade-level arithmetic and reasoning.",
    contextSentence: "This is a Math Kangaroo style practice question for Grade 5.",
    hints: ["Identify the operation first.", "Check units and compute carefully."],
    coach: "Correct. The answer is 68."
  },
  {
    id: "mk-g5-27",
    grade: 5,
    type: "kangaroo-g5",
    word: "63",
    prompt: "What is 9 × 7?",
    choices: ["63", "60", "67", "71"],
    answer: "63",
    definition: "Solve using grade-level arithmetic and reasoning.",
    contextSentence: "This is a Math Kangaroo style practice question for Grade 5.",
    hints: ["Identify the operation first.", "Check units and compute carefully."],
    coach: "Correct. The answer is 63."
  },
  {
    id: "mk-g5-28",
    grade: 5,
    type: "kangaroo-g5",
    word: "28",
    prompt: "A rectangle is 9 cm by 5 cm. What is its perimeter?",
    choices: ["28", "14", "45", "23"],
    answer: "28",
    definition: "Solve using grade-level arithmetic and reasoning.",
    contextSentence: "This is a Math Kangaroo style practice question for Grade 5.",
    hints: ["Identify the operation first.", "Check units and compute carefully."],
    coach: "Correct. The answer is 28."
  },
  {
    id: "mk-g5-29",
    grade: 5,
    type: "kangaroo-g5",
    word: "20",
    prompt: "A rectangle is 5 cm by 4 cm. What is its area?",
    choices: ["30", "9", "18", "20"],
    answer: "20",
    definition: "Solve using grade-level arithmetic and reasoning.",
    contextSentence: "This is a Math Kangaroo style practice question for Grade 5.",
    hints: ["Identify the operation first.", "Check units and compute carefully."],
    coach: "Correct. The answer is 20."
  },
  {
    id: "mk-g5-30",
    grade: 5,
    type: "kangaroo-g5",
    word: "7.5",
    prompt: "What is 1/2 of 15?",
    choices: ["9.5", "6.5", "7.5", "11.5"],
    answer: "7.5",
    definition: "Solve using grade-level arithmetic and reasoning.",
    contextSentence: "This is a Math Kangaroo style practice question for Grade 5.",
    hints: ["Identify the operation first.", "Check units and compute carefully."],
    coach: "Correct. The answer is 7.5."
  },
  {
    id: "mk-g6-11",
    grade: 6,
    type: "kangaroo-g6",
    word: "12",
    prompt: "What is 16 - 4?",
    choices: ["12", "14", "9", "17"],
    answer: "12",
    definition: "Use fractions, percentages, and equations at Grade 6 level.",
    contextSentence: "This is a Math Kangaroo style practice question for Grade 6.",
    hints: ["Translate words into numbers.", "Estimate first, then compute exactly."],
    coach: "Nice work. The answer is 12."
  },
  {
    id: "mk-g6-12",
    grade: 6,
    type: "kangaroo-g6",
    word: "22",
    prompt: "A rectangle has length 6 and width 5. What is its perimeter?",
    choices: ["22", "30", "11", "28"],
    answer: "22",
    definition: "Use fractions, percentages, and equations at Grade 6 level.",
    contextSentence: "This is a Math Kangaroo style practice question for Grade 6.",
    hints: ["Translate words into numbers.", "Estimate first, then compute exactly."],
    coach: "Nice work. The answer is 22."
  },
  {
    id: "mk-g6-13",
    grade: 6,
    type: "kangaroo-g6",
    word: "10",
    prompt: "50% of 20 is:",
    choices: ["20", "8", "13", "10"],
    answer: "10",
    definition: "Use fractions, percentages, and equations at Grade 6 level.",
    contextSentence: "This is a Math Kangaroo style practice question for Grade 6.",
    hints: ["Translate words into numbers.", "Estimate first, then compute exactly."],
    coach: "Nice work. The answer is 10."
  },
  {
    id: "mk-g6-14",
    grade: 6,
    type: "kangaroo-g6",
    word: "7/28",
    prompt: "Simplify the fraction 14/56.",
    choices: ["7/28", "7/29", "8/28", "6/28"],
    answer: "7/28",
    definition: "Use fractions, percentages, and equations at Grade 6 level.",
    contextSentence: "This is a Math Kangaroo style practice question for Grade 6.",
    hints: ["Translate words into numbers.", "Estimate first, then compute exactly."],
    coach: "Nice work. The answer is 7/28."
  },
  {
    id: "mk-g6-15",
    grade: 6,
    type: "kangaroo-g6",
    word: "12",
    prompt: "If x + 5 = 17, what is x?",
    choices: ["12", "10", "14", "16"],
    answer: "12",
    definition: "Use fractions, percentages, and equations at Grade 6 level.",
    contextSentence: "This is a Math Kangaroo style practice question for Grade 6.",
    hints: ["Translate words into numbers.", "Estimate first, then compute exactly."],
    coach: "Nice work. The answer is 12."
  },
  {
    id: "mk-g6-16",
    grade: 6,
    type: "kangaroo-g6",
    word: "10",
    prompt: "What is 14 - 4?",
    choices: ["10", "12", "7", "15"],
    answer: "10",
    definition: "Use fractions, percentages, and equations at Grade 6 level.",
    contextSentence: "This is a Math Kangaroo style practice question for Grade 6.",
    hints: ["Translate words into numbers.", "Estimate first, then compute exactly."],
    coach: "Nice work. The answer is 10."
  },
  {
    id: "mk-g6-17",
    grade: 6,
    type: "kangaroo-g6",
    word: "34",
    prompt: "A rectangle has length 11 and width 6. What is its perimeter?",
    choices: ["34", "66", "17", "40"],
    answer: "34",
    definition: "Use fractions, percentages, and equations at Grade 6 level.",
    contextSentence: "This is a Math Kangaroo style practice question for Grade 6.",
    hints: ["Translate words into numbers.", "Estimate first, then compute exactly."],
    coach: "Nice work. The answer is 34."
  },
  {
    id: "mk-g6-18",
    grade: 6,
    type: "kangaroo-g6",
    word: "9",
    prompt: "50% of 18 is:",
    choices: ["12", "7", "9", "18"],
    answer: "9",
    definition: "Use fractions, percentages, and equations at Grade 6 level.",
    contextSentence: "This is a Math Kangaroo style practice question for Grade 6.",
    hints: ["Translate words into numbers.", "Estimate first, then compute exactly."],
    coach: "Nice work. The answer is 9."
  },
  {
    id: "mk-g6-19",
    grade: 6,
    type: "kangaroo-g6",
    word: "7/35",
    prompt: "Simplify the fraction 14/70.",
    choices: ["7/35", "7/36", "8/35", "6/35"],
    answer: "7/35",
    definition: "Use fractions, percentages, and equations at Grade 6 level.",
    contextSentence: "This is a Math Kangaroo style practice question for Grade 6.",
    hints: ["Translate words into numbers.", "Estimate first, then compute exactly."],
    coach: "Nice work. The answer is 7/35."
  },
  {
    id: "mk-g6-20",
    grade: 6,
    type: "kangaroo-g6",
    word: "11",
    prompt: "If x + 5 = 16, what is x?",
    choices: ["15", "9", "13", "11"],
    answer: "11",
    definition: "Use fractions, percentages, and equations at Grade 6 level.",
    contextSentence: "This is a Math Kangaroo style practice question for Grade 6.",
    hints: ["Translate words into numbers.", "Estimate first, then compute exactly."],
    coach: "Nice work. The answer is 11."
  },
  {
    id: "mk-g6-21",
    grade: 6,
    type: "kangaroo-g6",
    word: "8",
    prompt: "What is 12 - 4?",
    choices: ["13", "10", "5", "8"],
    answer: "8",
    definition: "Use fractions, percentages, and equations at Grade 6 level.",
    contextSentence: "This is a Math Kangaroo style practice question for Grade 6.",
    hints: ["Translate words into numbers.", "Estimate first, then compute exactly."],
    coach: "Nice work. The answer is 8."
  },
  {
    id: "mk-g6-22",
    grade: 6,
    type: "kangaroo-g6",
    word: "34",
    prompt: "A rectangle has length 10 and width 7. What is its perimeter?",
    choices: ["34", "70", "17", "40"],
    answer: "34",
    definition: "Use fractions, percentages, and equations at Grade 6 level.",
    contextSentence: "This is a Math Kangaroo style practice question for Grade 6.",
    hints: ["Translate words into numbers.", "Estimate first, then compute exactly."],
    coach: "Nice work. The answer is 34."
  },
  {
    id: "mk-g6-23",
    grade: 6,
    type: "kangaroo-g6",
    word: "8",
    prompt: "50% of 16 is:",
    choices: ["11", "6", "8", "16"],
    answer: "8",
    definition: "Use fractions, percentages, and equations at Grade 6 level.",
    contextSentence: "This is a Math Kangaroo style practice question for Grade 6.",
    hints: ["Translate words into numbers.", "Estimate first, then compute exactly."],
    coach: "Nice work. The answer is 8."
  },
  {
    id: "mk-g6-24",
    grade: 6,
    type: "kangaroo-g6",
    word: "7/14",
    prompt: "Simplify the fraction 14/28.",
    choices: ["7/14", "7/15", "8/14", "6/14"],
    answer: "7/14",
    definition: "Use fractions, percentages, and equations at Grade 6 level.",
    contextSentence: "This is a Math Kangaroo style practice question for Grade 6.",
    hints: ["Translate words into numbers.", "Estimate first, then compute exactly."],
    coach: "Nice work. The answer is 7/14."
  },
  {
    id: "mk-g6-25",
    grade: 6,
    type: "kangaroo-g6",
    word: "10",
    prompt: "If x + 5 = 15, what is x?",
    choices: ["14", "8", "12", "10"],
    answer: "10",
    definition: "Use fractions, percentages, and equations at Grade 6 level.",
    contextSentence: "This is a Math Kangaroo style practice question for Grade 6.",
    hints: ["Translate words into numbers.", "Estimate first, then compute exactly."],
    coach: "Nice work. The answer is 10."
  },
  {
    id: "mk-g6-26",
    grade: 6,
    type: "kangaroo-g6",
    word: "13",
    prompt: "What is 17 - 4?",
    choices: ["13", "15", "10", "18"],
    answer: "13",
    definition: "Use fractions, percentages, and equations at Grade 6 level.",
    contextSentence: "This is a Math Kangaroo style practice question for Grade 6.",
    hints: ["Translate words into numbers.", "Estimate first, then compute exactly."],
    coach: "Nice work. The answer is 13."
  },
  {
    id: "mk-g6-27",
    grade: 6,
    type: "kangaroo-g6",
    word: "34",
    prompt: "A rectangle has length 9 and width 8. What is its perimeter?",
    choices: ["34", "72", "17", "40"],
    answer: "34",
    definition: "Use fractions, percentages, and equations at Grade 6 level.",
    contextSentence: "This is a Math Kangaroo style practice question for Grade 6.",
    hints: ["Translate words into numbers.", "Estimate first, then compute exactly."],
    coach: "Nice work. The answer is 34."
  },
  {
    id: "mk-g6-28",
    grade: 6,
    type: "kangaroo-g6",
    word: "7",
    prompt: "50% of 14 is:",
    choices: ["10", "5", "7", "14"],
    answer: "7",
    definition: "Use fractions, percentages, and equations at Grade 6 level.",
    contextSentence: "This is a Math Kangaroo style practice question for Grade 6.",
    hints: ["Translate words into numbers.", "Estimate first, then compute exactly."],
    coach: "Nice work. The answer is 7."
  },
  {
    id: "mk-g6-29",
    grade: 6,
    type: "kangaroo-g6",
    word: "7/21",
    prompt: "Simplify the fraction 14/42.",
    choices: ["7/21", "7/22", "8/21", "6/21"],
    answer: "7/21",
    definition: "Use fractions, percentages, and equations at Grade 6 level.",
    contextSentence: "This is a Math Kangaroo style practice question for Grade 6.",
    hints: ["Translate words into numbers.", "Estimate first, then compute exactly."],
    coach: "Nice work. The answer is 7/21."
  },
  {
    id: "mk-g6-30",
    grade: 6,
    type: "kangaroo-g6",
    word: "9",
    prompt: "If x + 5 = 14, what is x?",
    choices: ["11", "7", "9", "13"],
    answer: "9",
    definition: "Use fractions, percentages, and equations at Grade 6 level.",
    contextSentence: "This is a Math Kangaroo style practice question for Grade 6.",
    hints: ["Translate words into numbers.", "Estimate first, then compute exactly."],
    coach: "Nice work. The answer is 9."
  },
  {
    id: "mk-g7-11",
    grade: 7,
    type: "kangaroo-g7",
    word: "32",
    prompt: "Evaluate: 6^2 - 4.",
    choices: ["32", "29", "36", "10"],
    answer: "32",
    definition: "Use algebraic reasoning and patterns.",
    contextSentence: "This is a Math Kangaroo style practice question for Grade 7.",
    hints: ["Work step by step.", "Check by substitution when possible."],
    coach: "Correct answer: 32."
  },
  {
    id: "mk-g7-12",
    grade: 7,
    type: "kangaroo-g7",
    word: "5",
    prompt: "Solve: 2x + 3 = 13.",
    choices: ["7", "4", "5", "8"],
    answer: "5",
    definition: "Use algebraic reasoning and patterns.",
    contextSentence: "This is a Math Kangaroo style practice question for Grade 7.",
    hints: ["Work step by step.", "Check by substitution when possible."],
    coach: "Correct answer: 5."
  },
  {
    id: "mk-g7-13",
    grade: 7,
    type: "kangaroo-g7",
    word: "20",
    prompt: "A box has 4 rows with 5 items each. How many items total?",
    choices: ["20", "18", "23", "9"],
    answer: "20",
    definition: "Use algebraic reasoning and patterns.",
    contextSentence: "This is a Math Kangaroo style practice question for Grade 7.",
    hints: ["Work step by step.", "Check by substitution when possible."],
    coach: "Correct answer: 20."
  },
  {
    id: "mk-g7-14",
    grade: 7,
    type: "kangaroo-g7",
    word: "3",
    prompt: "What is 12 ÷ 4?",
    choices: ["2", "4", "3", "6"],
    answer: "3",
    definition: "Use algebraic reasoning and patterns.",
    contextSentence: "This is a Math Kangaroo style practice question for Grade 7.",
    hints: ["Work step by step.", "Check by substitution when possible."],
    coach: "Correct answer: 3."
  },
  {
    id: "mk-g7-15",
    grade: 7,
    type: "kangaroo-g7",
    word: "17",
    prompt: "The arithmetic sequence is 1, 4, 7, ... What is the 3rd term plus the 4th term?",
    choices: ["17", "14", "19", "23"],
    answer: "17",
    definition: "Use algebraic reasoning and patterns.",
    contextSentence: "This is a Math Kangaroo style practice question for Grade 7.",
    hints: ["Work step by step.", "Check by substitution when possible."],
    coach: "Correct answer: 17."
  },
  {
    id: "mk-g7-16",
    grade: 7,
    type: "kangaroo-g7",
    word: "12",
    prompt: "Evaluate: 4^2 - 4.",
    choices: ["8", "9", "16", "12"],
    answer: "12",
    definition: "Use algebraic reasoning and patterns.",
    contextSentence: "This is a Math Kangaroo style practice question for Grade 7.",
    hints: ["Work step by step.", "Check by substitution when possible."],
    coach: "Correct answer: 12."
  },
  {
    id: "mk-g7-17",
    grade: 7,
    type: "kangaroo-g7",
    word: "10",
    prompt: "Solve: 2x + 3 = 23.",
    choices: ["13", "9", "12", "10"],
    answer: "10",
    definition: "Use algebraic reasoning and patterns.",
    contextSentence: "This is a Math Kangaroo style practice question for Grade 7.",
    hints: ["Work step by step.", "Check by substitution when possible."],
    coach: "Correct answer: 10."
  },
  {
    id: "mk-g7-18",
    grade: 7,
    type: "kangaroo-g7",
    word: "25",
    prompt: "A box has 5 rows with 5 items each. How many items total?",
    choices: ["25", "23", "28", "10"],
    answer: "25",
    definition: "Use algebraic reasoning and patterns.",
    contextSentence: "This is a Math Kangaroo style practice question for Grade 7.",
    hints: ["Work step by step.", "Check by substitution when possible."],
    coach: "Correct answer: 25."
  },
  {
    id: "mk-g7-19",
    grade: 7,
    type: "kangaroo-g7",
    word: "3.6666666666666665",
    prompt: "What is 11 ÷ 3?",
    choices: ["6.666666666666666", "4.666666666666666", "2.6666666666666665", "3.6666666666666665"],
    answer: "3.6666666666666665",
    definition: "Use algebraic reasoning and patterns.",
    contextSentence: "This is a Math Kangaroo style practice question for Grade 7.",
    hints: ["Work step by step.", "Check by substitution when possible."],
    coach: "Correct answer: 3.6666666666666665."
  },
  {
    id: "mk-g7-20",
    grade: 7,
    type: "kangaroo-g7",
    word: "17",
    prompt: "The arithmetic sequence is 1, 4, 7, ... What is the 3rd term plus the 4th term?",
    choices: ["17", "14", "19", "23"],
    answer: "17",
    definition: "Use algebraic reasoning and patterns.",
    contextSentence: "This is a Math Kangaroo style practice question for Grade 7.",
    hints: ["Work step by step.", "Check by substitution when possible."],
    coach: "Correct answer: 17."
  },
  {
    id: "mk-g7-21",
    grade: 7,
    type: "kangaroo-g7",
    word: "0",
    prompt: "Evaluate: 2^2 - 4.",
    choices: ["6", "-3", "4", "0"],
    answer: "0",
    definition: "Use algebraic reasoning and patterns.",
    contextSentence: "This is a Math Kangaroo style practice question for Grade 7.",
    hints: ["Work step by step.", "Check by substitution when possible."],
    coach: "Correct answer: 0."
  },
  {
    id: "mk-g7-22",
    grade: 7,
    type: "kangaroo-g7",
    word: "9",
    prompt: "Solve: 2x + 3 = 21.",
    choices: ["11", "8", "9", "12"],
    answer: "9",
    definition: "Use algebraic reasoning and patterns.",
    contextSentence: "This is a Math Kangaroo style practice question for Grade 7.",
    hints: ["Work step by step.", "Check by substitution when possible."],
    coach: "Correct answer: 9."
  },
  {
    id: "mk-g7-23",
    grade: 7,
    type: "kangaroo-g7",
    word: "30",
    prompt: "A box has 6 rows with 5 items each. How many items total?",
    choices: ["30", "28", "33", "11"],
    answer: "30",
    definition: "Use algebraic reasoning and patterns.",
    contextSentence: "This is a Math Kangaroo style practice question for Grade 7.",
    hints: ["Work step by step.", "Check by substitution when possible."],
    coach: "Correct answer: 30."
  },
  {
    id: "mk-g7-24",
    grade: 7,
    type: "kangaroo-g7",
    word: "5",
    prompt: "What is 10 ÷ 2?",
    choices: ["4", "6", "5", "8"],
    answer: "5",
    definition: "Use algebraic reasoning and patterns.",
    contextSentence: "This is a Math Kangaroo style practice question for Grade 7.",
    hints: ["Work step by step.", "Check by substitution when possible."],
    coach: "Correct answer: 5."
  },
  {
    id: "mk-g7-25",
    grade: 7,
    type: "kangaroo-g7",
    word: "17",
    prompt: "The arithmetic sequence is 1, 4, 7, ... What is the 3rd term plus the 4th term?",
    choices: ["17", "14", "19", "23"],
    answer: "17",
    definition: "Use algebraic reasoning and patterns.",
    contextSentence: "This is a Math Kangaroo style practice question for Grade 7.",
    hints: ["Work step by step.", "Check by substitution when possible."],
    coach: "Correct answer: 17."
  },
  {
    id: "mk-g7-26",
    grade: 7,
    type: "kangaroo-g7",
    word: "45",
    prompt: "Evaluate: 7^2 - 4.",
    choices: ["45", "42", "49", "11"],
    answer: "45",
    definition: "Use algebraic reasoning and patterns.",
    contextSentence: "This is a Math Kangaroo style practice question for Grade 7.",
    hints: ["Work step by step.", "Check by substitution when possible."],
    coach: "Correct answer: 45."
  },
  {
    id: "mk-g7-27",
    grade: 7,
    type: "kangaroo-g7",
    word: "8",
    prompt: "Solve: 2x + 3 = 19.",
    choices: ["10", "7", "8", "11"],
    answer: "8",
    definition: "Use algebraic reasoning and patterns.",
    contextSentence: "This is a Math Kangaroo style practice question for Grade 7.",
    hints: ["Work step by step.", "Check by substitution when possible."],
    coach: "Correct answer: 8."
  },
  {
    id: "mk-g7-28",
    grade: 7,
    type: "kangaroo-g7",
    word: "15",
    prompt: "A box has 3 rows with 5 items each. How many items total?",
    choices: ["15", "13", "18", "8"],
    answer: "15",
    definition: "Use algebraic reasoning and patterns.",
    contextSentence: "This is a Math Kangaroo style practice question for Grade 7.",
    hints: ["Work step by step.", "Check by substitution when possible."],
    coach: "Correct answer: 15."
  },
  {
    id: "mk-g7-29",
    grade: 7,
    type: "kangaroo-g7",
    word: "3.75",
    prompt: "What is 15 ÷ 4?",
    choices: ["3.75", "4.75", "2.75", "6.75"],
    answer: "3.75",
    definition: "Use algebraic reasoning and patterns.",
    contextSentence: "This is a Math Kangaroo style practice question for Grade 7.",
    hints: ["Work step by step.", "Check by substitution when possible."],
    coach: "Correct answer: 3.75."
  },
  {
    id: "mk-g7-30",
    grade: 7,
    type: "kangaroo-g7",
    word: "17",
    prompt: "The arithmetic sequence is 1, 4, 7, ... What is the 3rd term plus the 4th term?",
    choices: ["17", "14", "19", "23"],
    answer: "17",
    definition: "Use algebraic reasoning and patterns.",
    contextSentence: "This is a Math Kangaroo style practice question for Grade 7.",
    hints: ["Work step by step.", "Check by substitution when possible."],
    coach: "Correct answer: 17."
  },
  {
    id: "mk-g8-11",
    grade: 8,
    type: "kangaroo-g8",
    word: "6",
    prompt: "Solve: 3x - 4 = 14.",
    choices: ["7", "4", "6", "9"],
    answer: "6",
    definition: "Apply algebra, percentages, and geometry relationships.",
    contextSentence: "This is a Math Kangaroo style practice question for Grade 8.",
    hints: ["Identify the formula before calculating.", "Use inverse operations to verify."],
    coach: "Well done. The answer is 6."
  },
  {
    id: "mk-g8-12",
    grade: 8,
    type: "kangaroo-g8",
    word: "9",
    prompt: "What is (3)^2?",
    choices: ["14", "5", "9", "6"],
    answer: "9",
    definition: "Apply algebra, percentages, and geometry relationships.",
    contextSentence: "This is a Math Kangaroo style practice question for Grade 8.",
    hints: ["Identify the formula before calculating.", "Use inverse operations to verify."],
    coach: "Well done. The answer is 9."
  },
  {
    id: "mk-g8-13",
    grade: 8,
    type: "kangaroo-g8",
    word: "13",
    prompt: "A right triangle has legs 5 and 12. What is its hypotenuse?",
    choices: ["13", "11", "12", "14"],
    answer: "13",
    definition: "Apply algebra, percentages, and geometry relationships.",
    contextSentence: "This is a Math Kangaroo style practice question for Grade 8.",
    hints: ["Identify the formula before calculating.", "Use inverse operations to verify."],
    coach: "Well done. The answer is 13."
  },
  {
    id: "mk-g8-14",
    grade: 8,
    type: "kangaroo-g8",
    word: "2.8000000000000003",
    prompt: "What is 20% of 14?",
    choices: ["2.8000000000000003", "1.8000000000000003", "4.800000000000001", "14"],
    answer: "2.8000000000000003",
    definition: "Apply algebra, percentages, and geometry relationships.",
    contextSentence: "This is a Math Kangaroo style practice question for Grade 8.",
    hints: ["Identify the formula before calculating.", "Use inverse operations to verify."],
    coach: "Well done. The answer is 2.8000000000000003."
  },
  {
    id: "mk-g8-15",
    grade: 8,
    type: "kangaroo-g8",
    word: "11",
    prompt: "If f(x)=x+6, what is f(5)?",
    choices: ["30", "9", "12", "11"],
    answer: "11",
    definition: "Apply algebra, percentages, and geometry relationships.",
    contextSentence: "This is a Math Kangaroo style practice question for Grade 8.",
    hints: ["Identify the formula before calculating.", "Use inverse operations to verify."],
    coach: "Well done. The answer is 11."
  },
  {
    id: "mk-g8-16",
    grade: 8,
    type: "kangaroo-g8",
    word: "4",
    prompt: "Solve: 3x - 4 = 8.",
    choices: ["5", "2", "4", "7"],
    answer: "4",
    definition: "Apply algebra, percentages, and geometry relationships.",
    contextSentence: "This is a Math Kangaroo style practice question for Grade 8.",
    hints: ["Identify the formula before calculating.", "Use inverse operations to verify."],
    coach: "Well done. The answer is 4."
  },
  {
    id: "mk-g8-17",
    grade: 8,
    type: "kangaroo-g8",
    word: "64",
    prompt: "What is (8)^2?",
    choices: ["64", "60", "69", "16"],
    answer: "64",
    definition: "Apply algebra, percentages, and geometry relationships.",
    contextSentence: "This is a Math Kangaroo style practice question for Grade 8.",
    hints: ["Identify the formula before calculating.", "Use inverse operations to verify."],
    coach: "Well done. The answer is 64."
  },
  {
    id: "mk-g8-18",
    grade: 8,
    type: "kangaroo-g8",
    word: "13",
    prompt: "A right triangle has legs 5 and 12. What is its hypotenuse?",
    choices: ["13", "11", "12", "14"],
    answer: "13",
    definition: "Apply algebra, percentages, and geometry relationships.",
    contextSentence: "This is a Math Kangaroo style practice question for Grade 8.",
    hints: ["Identify the formula before calculating.", "Use inverse operations to verify."],
    coach: "Well done. The answer is 13."
  },
  {
    id: "mk-g8-19",
    grade: 8,
    type: "kangaroo-g8",
    word: "2.8000000000000003",
    prompt: "What is 20% of 14?",
    choices: ["2.8000000000000003", "1.8000000000000003", "4.800000000000001", "14"],
    answer: "2.8000000000000003",
    definition: "Apply algebra, percentages, and geometry relationships.",
    contextSentence: "This is a Math Kangaroo style practice question for Grade 8.",
    hints: ["Identify the formula before calculating.", "Use inverse operations to verify."],
    coach: "Well done. The answer is 2.8000000000000003."
  },
  {
    id: "mk-g8-20",
    grade: 8,
    type: "kangaroo-g8",
    word: "15",
    prompt: "If f(x)=x+5, what is f(10)?",
    choices: ["15", "13", "16", "50"],
    answer: "15",
    definition: "Apply algebra, percentages, and geometry relationships.",
    contextSentence: "This is a Math Kangaroo style practice question for Grade 8.",
    hints: ["Identify the formula before calculating.", "Use inverse operations to verify."],
    coach: "Well done. The answer is 15."
  },
  {
    id: "mk-g8-21",
    grade: 8,
    type: "kangaroo-g8",
    word: "2",
    prompt: "Solve: 3x - 4 = 2.",
    choices: ["3", "0", "2", "5"],
    answer: "2",
    definition: "Apply algebra, percentages, and geometry relationships.",
    contextSentence: "This is a Math Kangaroo style practice question for Grade 8.",
    hints: ["Identify the formula before calculating.", "Use inverse operations to verify."],
    coach: "Well done. The answer is 2."
  },
  {
    id: "mk-g8-22",
    grade: 8,
    type: "kangaroo-g8",
    word: "49",
    prompt: "What is (7)^2?",
    choices: ["49", "45", "54", "14"],
    answer: "49",
    definition: "Apply algebra, percentages, and geometry relationships.",
    contextSentence: "This is a Math Kangaroo style practice question for Grade 8.",
    hints: ["Identify the formula before calculating.", "Use inverse operations to verify."],
    coach: "Well done. The answer is 49."
  },
  {
    id: "mk-g8-23",
    grade: 8,
    type: "kangaroo-g8",
    word: "17",
    prompt: "A right triangle has legs 8 and 15. What is its hypotenuse?",
    choices: ["17", "16", "18", "20"],
    answer: "17",
    definition: "Apply algebra, percentages, and geometry relationships.",
    contextSentence: "This is a Math Kangaroo style practice question for Grade 8.",
    hints: ["Identify the formula before calculating.", "Use inverse operations to verify."],
    coach: "Well done. The answer is 17."
  },
  {
    id: "mk-g8-24",
    grade: 8,
    type: "kangaroo-g8",
    word: "2.8000000000000003",
    prompt: "What is 20% of 14?",
    choices: ["2.8000000000000003", "1.8000000000000003", "4.800000000000001", "14"],
    answer: "2.8000000000000003",
    definition: "Apply algebra, percentages, and geometry relationships.",
    contextSentence: "This is a Math Kangaroo style practice question for Grade 8.",
    hints: ["Identify the formula before calculating.", "Use inverse operations to verify."],
    coach: "Well done. The answer is 2.8000000000000003."
  },
  {
    id: "mk-g8-25",
    grade: 8,
    type: "kangaroo-g8",
    word: "12",
    prompt: "If f(x)=x+4, what is f(8)?",
    choices: ["12", "10", "13", "32"],
    answer: "12",
    definition: "Apply algebra, percentages, and geometry relationships.",
    contextSentence: "This is a Math Kangaroo style practice question for Grade 8.",
    hints: ["Identify the formula before calculating.", "Use inverse operations to verify."],
    coach: "Well done. The answer is 12."
  },
  {
    id: "mk-g8-26",
    grade: 8,
    type: "kangaroo-g8",
    word: "7",
    prompt: "Solve: 3x - 4 = 17.",
    choices: ["8", "5", "7", "10"],
    answer: "7",
    definition: "Apply algebra, percentages, and geometry relationships.",
    contextSentence: "This is a Math Kangaroo style practice question for Grade 8.",
    hints: ["Identify the formula before calculating.", "Use inverse operations to verify."],
    coach: "Well done. The answer is 7."
  },
  {
    id: "mk-g8-27",
    grade: 8,
    type: "kangaroo-g8",
    word: "36",
    prompt: "What is (6)^2?",
    choices: ["36", "32", "41", "12"],
    answer: "36",
    definition: "Apply algebra, percentages, and geometry relationships.",
    contextSentence: "This is a Math Kangaroo style practice question for Grade 8.",
    hints: ["Identify the formula before calculating.", "Use inverse operations to verify."],
    coach: "Well done. The answer is 36."
  },
  {
    id: "mk-g8-28",
    grade: 8,
    type: "kangaroo-g8",
    word: "13",
    prompt: "A right triangle has legs 5 and 12. What is its hypotenuse?",
    choices: ["13", "11", "12", "14"],
    answer: "13",
    definition: "Apply algebra, percentages, and geometry relationships.",
    contextSentence: "This is a Math Kangaroo style practice question for Grade 8.",
    hints: ["Identify the formula before calculating.", "Use inverse operations to verify."],
    coach: "Well done. The answer is 13."
  },
  {
    id: "mk-g8-29",
    grade: 8,
    type: "kangaroo-g8",
    word: "2.8000000000000003",
    prompt: "What is 20% of 14?",
    choices: ["2.8000000000000003", "1.8000000000000003", "4.800000000000001", "14"],
    answer: "2.8000000000000003",
    definition: "Apply algebra, percentages, and geometry relationships.",
    contextSentence: "This is a Math Kangaroo style practice question for Grade 8.",
    hints: ["Identify the formula before calculating.", "Use inverse operations to verify."],
    coach: "Well done. The answer is 2.8000000000000003."
  },
  {
    id: "mk-g8-30",
    grade: 8,
    type: "kangaroo-g8",
    word: "9",
    prompt: "If f(x)=x+3, what is f(6)?",
    choices: ["10", "7", "9", "18"],
    answer: "9",
    definition: "Apply algebra, percentages, and geometry relationships.",
    contextSentence: "This is a Math Kangaroo style practice question for Grade 8.",
    hints: ["Identify the formula before calculating.", "Use inverse operations to verify."],
    coach: "Well done. The answer is 9."
  }

];
