-- Phase: per-student teacher settings
ALTER TABLE students
  ADD COLUMN IF NOT EXISTS font_size    TEXT    NOT NULL DEFAULT 'small',
  ADD COLUMN IF NOT EXISTS test_length  INTEGER NOT NULL DEFAULT 10,
  ADD COLUMN IF NOT EXISTS audio_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS audio_rate   NUMERIC(4,2) NOT NULL DEFAULT 0.88;
